# This workflow will Publish the package to PyPi
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Setup Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        poetry install
    - name: Publishing to PyPi
      env:
        PYPI_USER: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASS: ${{ secrets.PYPI_PASSWORD }}
      run: |
         poetry build
         poetry publish -u $PYPI_USER  -p $PYPI_PASS
